places = ["Crato", "Türkiye", "Kazakhstan", "Thailand", "Ulaanbaatar"]
sorted(places)
print(places)
sorted(places, reverse=True)
print(f"{sorted(places, reverse=True)} -> test for our sorted function")
places.reverse()
print(places)
places.reverse()
print(f"{places} -> re-reversing it")
places.sort()
print(places)
places.sort(reverse=True)
print(f"{places} -> reverse sorting it")
print(len(places))